#Configuration
#Update frequency, in milliseconds (300000 = 5 minutes)
cache_update_frequency: 300000
#Message format, %member% is replaced with the member display name, %message% is replaced with the message
#If Vault is installed, %prefix% and %suffix% may be used for the player's prefix and suffix, respectively
default_name_color: "&b"
#Here's a vanilla style template for those without prefixes:
#message_format: "&f<%member%&f> %message%"
message_format: "&f%prefix% %member% %suffix%&8>&f %message%"
#NOTE: Adding hover text may break some plugins! If you're having issues, set this to no
hover_text: yes
#If enabled, will not cancel the chat event, increasing plugin compatibility
#Note that this will cause the server console to see username only, not member name
keep_original_message_event: no
#If enabled, will make sure DiscordSRV (if installed) sees
#messages sent through pluralkitmc when hover_text is enabled.
#REQUIRES RespectChatPlugins to be true, or else you will encounter double messages!
discordsrv_compatibility: yes
#Use member names for %displayname% in DiscordSRV
#(Requires hover_text and discordsrv_compatibility enabled)
discordsrv_use_member_names: yes
#This determines whether PluralKitMC saves system & member data to disk for fastest retrieval
cache_data: true
#datatype: <flat/db>
datatype: flat
#Only if datatype is set to DB
db_username: username
db_password: password
db_database: mydb
db_url: example.org
db_port: 3306
#Only if datatype is set to flat
players:
  cf173d12-c079-4213-81f0-9daa0acfd9bd:
    system: bpray